<style>
    table {
        width: 100%;
        text-align: center;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }


    .footer {
        position: fixed;
        bottom: 0;
    }

</style>
<h1 style="text-align: center; border-bottom: 1px solid black; font-size: 20px"><span style="color: red">Data</span>trix
    Soft
</h1>
<h1 style="text-align: center; font-size: 16px">Report Generated By <span style="color: #6B6B6B ">PTSS</span>
</h1>

<h4 style="font-size: 18px">Detail of {{ $department->name }} Department</h4>
<small style="float: right">{{ date(now('asia/dhaka')) }}</small>

<br><br>
<strong>
    <cpation style="color: #ee5f5b">Overall View</cpation>
</strong><br>
<table>
    <tr>
        <th>Projects</th>
        <th>Teams</th>
        <th>Completed Projects</th>
        <th>Pending Project</th>
    </tr>
    <tr>
        <td>{{ count($department->projects) }}</td>
        <td>{{ count($department->teams) }}</td>
        <td>{{ count($department->projects->where('status', 2)) }}</td>
        <td>{{ count($department->projects->where('status', 0)) }}</td>
    </tr>
</table>
<br><br>


<strong>
    <cpation style="color: #ee5f5b">Projects</cpation>
</strong>
<table>

    <tr>
        <th>#</th>
        <th>Projects</th>
        <th>Status</th>
        <th>Created_at</th>
    </tr>
    @if(count($department->projects) != 0 )
        @foreach($department->projects as $key => $project)
            <tr>
                <td>{{ $key +=1 }}</td>
                <td>{{ $project->title }}</td>
                <td>{{ $project->status }}</td>
                <td>{{ $project->created_at }}</td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="3" style="color: red; font-size: 14px">|| Currently has No Project ||</td>
        </tr>
    @endif
</table>
<br><br>


<strong>
    <cpation style="color: #ee5f5b">Teams</cpation>
</strong>
<table>

    <tr>
        <th>#</th>
        <th>Teams</th>
        <th>Created_at</th>
    </tr>
    @if(count($department->teams) != 0 )
        @foreach($department->teams as $key => $team)
            <tr>
                <td>{{ $key +=1 }}</td>
                <td>{{ $team->name }}</td>
                <td>{{ $team->created_at }}</td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="3" style="color: red; font-size: 14px">|| Currently has No Team ||</td>
        </tr>
    @endif
</table>

<div class="footer">
    <p style="text-align: center; border-bottom: 1px solid black; color: darkgray">Coyright <i
            class="fa fa-copyright"></i> 2019 DataTrix Soft. All rights reserved. Design and Developed by Md. Shahadat
        Hossain</p>
</div>
