<style>
    table {
        width: 100%;
        text-align: center;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }


    .footer {
        position: fixed;
        bottom: 0;
    }

</style>
<h1 style="text-align: center; border-bottom: 1px solid black; font-size: 20px"><span style="color: red">Data</span>trix
    Soft
</h1>
<h1 style="text-align: center; font-size: 16px">Report Generated By <span style="color: #6B6B6B ">PTSS</span>
</h1>

<h4 style="font-size: 18px">Detail of <span style="color: #0c525d">"{{ $project->title }}"</span> Project</h4>
<small style="float: right">{{ date(now('asia/dhaka')) }}</small>
@php
    use Carbon\Carbon;
    $date = Carbon::parse($project->created_at);
    $now = Carbon::now();
    $diff = $date->diffInDays($now);
@endphp
<br><br>
<strong>
    <cpation style="color: #ee5f5b">Overall View</cpation>
</strong><br>
<table>
    <tr>
        <th>Estimated Project Duration</th>
        <th>Estimated Budget</th>
        <th>Departments</th>
        <th>Team</th>
        <th>Description</th>
    </tr>
    @if($project)
    <tr>
        <td>
            <strong style="text-align: center">{{ $project->estimated_project_duration }} days
                <br> <b>Gone:</b> ({{ $diff}}) days
                <br> <b>Left:</b> ({{$project->estimated_project_duration - $diff  }}) days
            </strong>
        </td>
        <td>{{ $project->estimated_budget }}/=</td>
        @if(count($project->departments) != 0)
        <td>
            @foreach($project->departments as $department)
                <strong style="text-align: center">{{ $department->name }}</strong>
                <br>
            @endforeach
        </td>
        @else
            <td style="color: red; font-size: 14px; ">|Dept. Not set Yet|</td>
        @endif
        @if(count($project->teams) != 0)
        <td>
            @foreach($project->teams as $team)
                <strong style="text-align: center">{{ $team->name }}</strong>
            @endforeach
        </td>
        @else
            <td style="color: red; font-size: 14px; ">|Not assigned Yet|</td>
            @endif
        <td>{{ $project->description }}</td>
    </tr>
        @else
        <tr>
            <td colspan="4" style="color: red; font-size: 14px">|| Currently has No Project ||</td>
        </tr>
        @endif
</table>
<br><br>


<strong>
    <cpation style="color: #ee5f5b">Requirements</cpation>
</strong>
<table>

    <tr>
        <th>#</th>
        <th>Requirement</th>
        <th>Status</th>
        <th>Percentage</th>
    </tr>
    @if(count($project->requirements) != 0 )
        @foreach($project->requirements as $key => $requirement)
            <tr>
                <th scope="row">{{ $key++ }}</th>
                <td>{{ $requirement->name }}</td>
                <td>{{ $requirement->status }}</td>
                <td>{{ $requirement->percentage }}</td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="4" style="color: red; font-size: 14px">|| Currently has No Requirement ||</td>
        </tr>
    @endif
</table>
<br><br>


<strong>
    <cpation style="color: #ee5f5b">Files</cpation>
</strong>
<table>
    <tr>
        <th>#</th>
        <th>Filename</th>
    </tr>
    @if(count($project->files) != 0 )
        @foreach($project->files as $key => $file)
            <tr>
                <td>{{ $key++ }}</td>
                <td>{{ $file->filename }}</td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="2" style="color: red; font-size: 14px">|| Currently has No File ||</td>
        </tr>
    @endif
</table>

<div class="footer">
    <p style="text-align: center; border-bottom: 1px solid black; color: darkgray">Coyright <i
            class="fa fa-copyright"></i> 2019 DataTrix Soft. All rights reserved. Design and Developed by Md. Shahadat
        Hossain</p>
</div>
